# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku.ui'
#
# Created: Mon Aug  5 23:13:56 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sudoku(object):
    def setupUi(self, Sudoku):
        Sudoku.setObjectName(_fromUtf8("Sudoku"))
        Sudoku.resize(725, 700)
        self.centralWidget = QtGui.QWidget(Sudoku)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 171, 171))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.bloque1 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.bloque1.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque1.setMargin(0)
        self.bloque1.setObjectName(_fromUtf8("bloque1"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(0, 580, 581, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 600, 551, 61))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.gridTeclado = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.gridTeclado.setMargin(0)
        self.gridTeclado.setObjectName(_fromUtf8("gridTeclado"))
        self.line_4 = QtGui.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(190, 20, 20, 551))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(380, 20, 20, 551))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_8 = QtGui.QFrame(self.centralWidget)
        self.line_8.setGeometry(QtCore.QRect(20, 190, 551, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.centralWidget)
        self.line_9.setGeometry(QtCore.QRect(20, 380, 551, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(210, 20, 171, 171))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.bloque2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.bloque2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque2.setMargin(0)
        self.bloque2.setObjectName(_fromUtf8("bloque2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(400, 20, 171, 171))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.bloque3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.bloque3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque3.setMargin(0)
        self.bloque3.setObjectName(_fromUtf8("bloque3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 210, 171, 171))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.bloque4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.bloque4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque4.setMargin(0)
        self.bloque4.setObjectName(_fromUtf8("bloque4"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(210, 210, 171, 171))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.bloque5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.bloque5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque5.setMargin(0)
        self.bloque5.setObjectName(_fromUtf8("bloque5"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(400, 210, 171, 171))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.bloque6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.bloque6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque6.setMargin(0)
        self.bloque6.setObjectName(_fromUtf8("bloque6"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 400, 171, 171))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.bloque7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.bloque7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque7.setMargin(0)
        self.bloque7.setObjectName(_fromUtf8("bloque7"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(210, 400, 171, 171))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.bloque8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.bloque8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque8.setMargin(0)
        self.bloque8.setObjectName(_fromUtf8("bloque8"))
        self.gridLayoutWidget_9 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(400, 400, 171, 171))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.bloque9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.bloque9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.bloque9.setMargin(0)
        self.bloque9.setObjectName(_fromUtf8("bloque9"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(580, 20, 131, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.LayoutCronometro = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.LayoutCronometro.setMargin(0)
        self.LayoutCronometro.setObjectName(_fromUtf8("LayoutCronometro"))
        Sudoku.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Sudoku)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 725, 20))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuCerrar = QtGui.QMenu(self.menuBar)
        self.menuCerrar.setObjectName(_fromUtf8("menuCerrar"))
        Sudoku.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(Sudoku)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        Sudoku.setStatusBar(self.statusBar)
        self.actionMenu = QtGui.QAction(Sudoku)
        self.actionMenu.setObjectName(_fromUtf8("actionMenu"))
        self.actionVerificar_Soluci_n = QtGui.QAction(Sudoku)
        self.actionVerificar_Soluci_n.setObjectName(_fromUtf8("actionVerificar_Soluci_n"))
        self.actionGuardar_partida = QtGui.QAction(Sudoku)
        self.actionGuardar_partida.setObjectName(_fromUtf8("actionGuardar_partida"))
        self.actionVolver_al_men_principal = QtGui.QAction(Sudoku)
        self.actionVolver_al_men_principal.setObjectName(_fromUtf8("actionVolver_al_men_principal"))
        self.actionSalir = QtGui.QAction(Sudoku)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.menuMenu.addAction(self.actionVerificar_Soluci_n)
        self.menuMenu.addAction(self.actionGuardar_partida)
        self.menuCerrar.addAction(self.actionVolver_al_men_principal)
        self.menuCerrar.addAction(self.actionSalir)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuCerrar.menuAction())

        self.retranslateUi(Sudoku)
        QtCore.QMetaObject.connectSlotsByName(Sudoku)

    def retranslateUi(self, Sudoku):
        Sudoku.setWindowTitle(_translate("Sudoku", "Sudoku", None))
        self.menuMenu.setTitle(_translate("Sudoku", "Menu", None))
        self.menuCerrar.setTitle(_translate("Sudoku", "Cerrar", None))
        self.actionMenu.setText(_translate("Sudoku", "Verificar solución", None))
        self.actionVerificar_Soluci_n.setText(_translate("Sudoku", "Verificar Solución", None))
        self.actionGuardar_partida.setText(_translate("Sudoku", "Guardar partida", None))
        self.actionVolver_al_men_principal.setText(_translate("Sudoku", "Volver al menú principal", None))
        self.actionSalir.setText(_translate("Sudoku", "Salir", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Sudoku = QtGui.QMainWindow()
    ui = Ui_Sudoku()
    ui.setupUi(Sudoku)
    Sudoku.show()
    sys.exit(app.exec_())

